(source gnu)
(source melpa)
(source org)

(package "org-btw" "0" "Custom org-mode exporters and settings.")
(files "org-btw*.el" "ox-pelican.el" "ox-latex+.el" "org-ref+.el")

(depends-on "cask")
(depends-on "cl-lib")
(depends-on "org-plus-contrib")
(depends-on "ox-gfm")
(depends-on "s")
(depends-on "f")
(depends-on "projectile")
(depends-on "string-inflection")
(depends-on "org-ref")
(depends-on "markdown-mode")
