(define-package "org-btw" "0" "Custom org-mode exporters and settings."
  '((markdown-mode nil)
    (org-ref nil)
    (string-inflection nil)
    (projectile nil)
    (s nil)
    (ox-gfm nil)
    (org-plus-contrib nil)
    (cl-lib nil)
    (cask nil)))
