name: Testing Workflow
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - '26.3'
          - 'snapshot'
        cask_version:
          - '0.8.4'
          - 'snapshot'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - uses: cask/setup-cask@master
        with:
          version: ${{ matrix.cask_version }}

      - name: Run tests
        run: |
          make elpa
          make test
